version: "3.9"

services:

  webapp:
    image: verevkinaee/work_4
    command: flask run -h 0.0.0.0 -p 5000
    restart: always
    environment:
      FLASK_ENV: 'development'
      FLASK_APP: game.app:app
    volumes:
      - ../geme/:/game/game/
